### ISSUE TITLE
Error: EPERM: operation not permitted, symlink 'Versions/A/Headers/'

### ISSUE THREAD

**Issue by hughknaus** [newrelic/newrelic-cordova-plugin#32]
When running `ionic cordova prepare` I receive this error:

> Installing "newrelic-cordova-plugin" for android
> Failed to install 'newrelic-cordova-plugin': Error: EPERM: operation not permitted, symlink 'Versions/A/Headers/' -> 'plugins/newrelic-cordova-plugin/libs/ios/NewRelicAgent.framework/Headers'
>     at Object.symlinkSync (node:fs:1705:3)
>     at module.exports (C:\_projects\AssistNG\plugins\newrelic-cordova-plugin\hooks\ios\before_plugin_install.js:12:12)
>     at runScriptViaModuleLoader (C:\Users\hknaus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:32)
>     at runScript (C:\Users\hknaus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:136:12)
>     at C:\Users\hknaus\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:108:40
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Failed to restore plugin "newrelic-cordova-plugin". You might need to try adding it again. Error: Error: EPERM: operation not permitted, symlink 'Versions/A/Headers/' -> 'plugins/newrelic-cordova-plugin/libs/ios/NewRelicAgent.framework/Headers'

All other Cordova plugins install without issue.

**Comment by ndesai-newrelic** [comment]
@hughknaus we are updating this plugin and it will fix the issue.

**Comment by hughknaus** [comment]
@ndesai-newrelic would you happen to also be creating a plugin for Capacitor?  We're migrating to Capacitor and would like to continue using NewRelic.

**Comment by ndesai-newrelic** [comment]
@hughknaus yes, we are developing capacitor plugin for newrelic.

**Comment by ndesai-newrelic** [comment]
@hughknaus newrelic capacitor plugin is available now. https://www.npmjs.com/package/@newrelic/newrelic-capacitor-plugin . Please share your feedback us once you integrate with your app
