### ISSUE TITLE
Unable to compile app with latest code

### ISSUE THREAD

**Issue by Karthikeyan-SBS** [newrelic/newrelic-cordova-plugin#80]
Hello newrelic team,

With recent builds i am getting below error with my configuration. Any help to point me what i am missing will be much appreciated.

in my package.json I have

```
my configuration:

devDependencies:
"newrelic-cordova-plugin": "git+https://github.com/newrelic/newrelic-cordova-plugin.git",

cordova:
 "newrelic-cordova-plugin": {
                "IOS_APP_TOKEN": "xx-NRMA",
                "ANDROID_APP_TOKEN": "xx-NRMA",
                "PLUGIN_VERSION": "5.0.0",
                "ANDROID_AGENT_VER": "6.11.1"
            }


Compilation out

:CordovaLib:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.


> Task :app:compileReleaseJavaWithJavac
\product\build\release\platforms\android\app\src\main\java\com\newrelic\cordova\plugin\NewRelicCordovaPlugin.java:14: error: cannot find symbol
import com.newrelic.agent.android.HttpHeaders;
                                 ^
  symbol:   class HttpHeaders
  location: package com.newrelic.agent.android
\product\build\release\platforms\android\app\src\main\java\com\newrelic\cordova\plugin\NewRelicCordovaPlugin.java:460: error: cannot find symbol
                    NewRelic.addHTTPHeadersTrackingFor(headerList);
                            ^
  symbol:   method addHTTPHeadersTrackingFor(List<String>)
  location: class NewRelic
\product\build\release\platforms\android\app\src\main\java\com\newrelic\cordova\plugin\NewRelicCordovaPlugin.java:465: error: cannot find symbol
                    List<String> arr = new ArrayList<>(HttpHeaders.getInstance().getHttpHeaders());
                                                       ^
  symbol:   variable HttpHeaders
  location: class NewRelicCordovaPlugin
```

Any Help to point what i am missing will be helpful.

Thanks
Kay

**Comment by ndesai-newrelic** [comment]
@Karthikeyan-SBS can you update android agent version to 7.2.0 or higher?

**Comment by Karthikeyan-SBS** [comment]
I am using  "cordova-android": "^10.1.2", we are in process ofupgrading to 12.. but not ready yet.

**Comment by Karthikeyan-SBS** [comment]
Please say which verion i need to use? is it 7.2.0?

**Comment by Karthikeyan-SBS** [comment]
I tried with

"PLUGIN_VERSION": "6.0.0",
 "ANDROID_AGENT_VER": "7.2.0"

getting

Caused by: java.lang.NoClassDefFoundError: com/android/build/api/variant/AndroidComponentsExtension
        at java.desktop/com.sun.beans.introspect.MethodInfo.get(MethodInfo.java:70)
        at java.desktop/com.sun.beans.introspect.ClassInfo.getMethods(ClassInfo.java:71)
        at com.newrelic.agent.android.NewRelicGradlePlugin.apply(NewRelicGradlePlugin.groovy:45)
        at com.newrelic.agent.android.NewRelicGradlePlugin.apply(NewRelicGradlePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:146)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:167)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:43)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:98)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:190)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)

I am using gradle 7.1.1

**Comment by ndesai-newrelic** [comment]
@Karthikeyan-SBS If updating your Gradle version is not possible, please continue using your current Gradle version.  To utilize the lower version gradle , you need to update the New Relic **classpath** 6.11.0 and lower in the build.gradle file at the project level.

**Comment by Karthikeyan-SBS** [comment]
Thanks @ndesai-newrelic 

I upgrade my  gradle plugin version in config.xml now its working.
<preference name="AndroidGradlePluginVersion" value="7.4.2" />

Thanks again

**Comment by ndesai-newrelic** [comment]
@Karthikeyan-SBS  can I close this?

**Comment by Karthikeyan-SBS** [comment]
Sure..all good
